apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-vault-config-operator
  namespace: argocd
spec:
  project: security
  source:
    repoURL: https://github.com/hongyuanlei/security-vault
    targetRevision: master
    path: vault-config-operator
    helm:
      valueFiles:
        - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
#      - ServerSideApply=true