apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-prometheus-stack
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://github.com/hongyuanlei/observability-promethues
    targetRevision: master
    path: prometheus
    helm:
      chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
#      version: 73.2.3
      valueFiles:
        - dev-values.yaml
        - common-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true