apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-prometheus-pushgateway
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://github.com/hongyuanlei/observability-promethues
    targetRevision: master
    path: prometheus-pushgateway
    helm:
      valueFiles:
        - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
#      - ServerSideApply=true