apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: main
    chart: kube-prometheus-stack
    helm:
      valueFiles:
#        - https://raw.githubusercontent.com/your-org/observability-prometheus/main/charts/prometheus-stack/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true