apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-kotlin-app
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: https://github.com/hongyuanlei/my-kotlin-app
    targetRevision: dev
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true